server:
  port: 8088

spring:
  application:
    name: client-1


  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
      discovery:
        instanceId: ${spring.application.name}:${server.port}
        healthCheckInterval: 3s
#        reactive:
#          enabled: false
#        blocking:
#          enabled: true

    loadbalancer:
      health-check:
        refetch-instances: true
        refetch-instances-interval: 5s     # interval for refetch-instances
        repeat-health-check: true         # no need as instances will be refetched
        interval: 2s                      # Interval for HealthCheck
      ribbon:
        enabled: false
      cache:
        ttl: 20s
        enabled: true
