server:
  port: 9082

spring:
  application:
    name: client-1
#  config:
#    import: "optional:consul:localhost:8500"
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
      discovery:
        instanceId: ${spring.application.name}:${server.port}
        healthCheckInterval: 3s

    loadbalancer:
      cache:
        ttl: 3s

#        healthCheckPath: /custom-health-check
#        healthCheckInterval: 10s




