server:
  port: 9082

spring:
  application:
    name: client-1

  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
      discovery:
        instanceId: ${spring.application.name}:${server.port}
        healthCheckInterval: 3s

    loadbalancer:
      cache:
        ttl: 1s
