spring:  
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true      # load-balance
      routes:
        - id: feign-client
          uri: lb://feign-client
          predicates:
            - Path=/feign/**
          filters:
            - RewritePath=/feign/(?<path>.*), /$\{path}

        - id: circuitbreak-client
          uri: lb://circuitbreak-client
          predicates:
            - Path=/circuitbreak/**
          filters:
            - RewritePath=/circuitbreak/(?<path>.*), /$\{path}

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*), /$\{path}


logging.level.com.netflix: DEBUG
    
management:
  security:
    enabled: false